insert into hymn.sys_core_account (id, name, username, password, online_rule, active, admin, root,
                                   leader_id, org_id, role_id, create_by_id, create_by,
                                   modify_by_id, modify_by, create_date, modify_date)
values ('911c60ea5d62420794d86eeecfddce7c', 'system admin', 'system admin', '', '', true, true,
        true, null, 'b18245e9d690461190172b6cb90c46ac', '301c35c23be449abb5bdf6c80b6878af',
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00');
insert into hymn.sys_core_org (id, name, director_id, deputy_director_id, parent_id,
                               create_by_id, create_by, modify_by_id, modify_by, create_date,
                               modify_date)
values ('b18245e9d690461190172b6cb90c46ac', '根组织', null, null, null,
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00');
insert into hymn.sys_core_role (id, name, remark, create_by_id, create_by, modify_by_id,
                                modify_by, create_date, modify_date)
values ('301c35c23be449abb5bdf6c80b6878af', '管理员权限', '', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '911c60ea5d62420794d86eeecfddce7c', 'system admin', '2020-01-01 00:00:00',
        '2020-01-01 00:00:00');

insert into hymn.sys_core_b_object (id, name, api, source_table, active, module_api, remark,
                                    create_by_id, create_by, modify_by_id, modify_by, create_date,
                                    modify_date)
values ('bcf5f00c2e6c494ea2318912a639031a', '用户', 'account', 'sys_core_account', true, 'core',
        '用户表',
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00'),
       ('53e9c36723dc4e3db1faf396fdb3f1d2', '角色', 'role', 'sys_core_role', true, 'core',
        '角色表',
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00'),
       ('c9c6cc327c614c96b8d6f5af1fee6442', '组织', 'org', 'sys_core_org', true, 'core',
        '组织表',
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00'),
       ('09da56a7de514895aea5c596820d0ced', '业务类型', 'business_type',
        'sys_core_b_object_type', true,
        'core', '自定义对象业务类型表',
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00')
;

insert into hymn.sys_core_dict (id, field_id, parent_dict_id, name, api, remark, create_by_id,
                                create_by, modify_by_id, modify_by, create_date, modify_date)
values ('4a6010cceea948d6856aac09e8aa19c0', null, null, '锁定状态', 'lock_state_dict', '系统标准字段锁定状态',
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00');

insert into hymn.sys_core_dict_item (id, dict_id, name, code, parent_code, create_by_id, create_by,
                                     modify_by_id, modify_by, create_date, modify_date)
values ('c31ec080066a432e9d1399b912c417c7', '4a6010cceea948d6856aac09e8aa19c0', '未锁定', '0', null,
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00'),
       ('273d19578032400aba689fb0fa40f912', '4a6010cceea948d6856aac09e8aa19c0', '已锁定', '1', null,
        '911c60ea5d62420794d86eeecfddce7c', 'system admin', '911c60ea5d62420794d86eeecfddce7c',
        'system admin', '2020-01-01 00:00:00', '2020-01-01 00:00:00');

insert into hymn.sys_core_table_obj_mapping (table_name, obj_api)
values ('sys_core_data_table_001', null),
       ('sys_core_data_table_002', null),
       ('sys_core_data_table_003', null),
       ('sys_core_data_table_004', null),
       ('sys_core_data_table_005', null),
       ('sys_core_data_table_006', null),
       ('sys_core_data_table_007', null),
       ('sys_core_data_table_008', null),
       ('sys_core_data_table_009', null),
       ('sys_core_data_table_010', null),
       ('sys_core_data_table_011', null),
       ('sys_core_data_table_012', null),
       ('sys_core_data_table_013', null),
       ('sys_core_data_table_014', null),
       ('sys_core_data_table_015', null),
       ('sys_core_data_table_016', null),
       ('sys_core_data_table_017', null),
       ('sys_core_data_table_018', null),
       ('sys_core_data_table_019', null),
       ('sys_core_data_table_020', null),
       ('sys_core_data_table_021', null),
       ('sys_core_data_table_022', null),
       ('sys_core_data_table_023', null),
       ('sys_core_data_table_024', null),
       ('sys_core_data_table_025', null),
       ('sys_core_data_table_026', null),
       ('sys_core_data_table_027', null),
       ('sys_core_data_table_028', null),
       ('sys_core_data_table_029', null),
       ('sys_core_data_table_030', null),
       ('sys_core_data_table_031', null),
       ('sys_core_data_table_032', null),
       ('sys_core_data_table_033', null),
       ('sys_core_data_table_034', null),
       ('sys_core_data_table_035', null),
       ('sys_core_data_table_036', null),
       ('sys_core_data_table_037', null),
       ('sys_core_data_table_038', null),
       ('sys_core_data_table_039', null),
       ('sys_core_data_table_040', null),
       ('sys_core_data_table_041', null),
       ('sys_core_data_table_042', null),
       ('sys_core_data_table_043', null),
       ('sys_core_data_table_044', null),
       ('sys_core_data_table_045', null),
       ('sys_core_data_table_046', null),
       ('sys_core_data_table_047', null),
       ('sys_core_data_table_048', null),
       ('sys_core_data_table_049', null),
       ('sys_core_data_table_050', null),
       ('sys_core_data_table_051', null),
       ('sys_core_data_table_052', null),
       ('sys_core_data_table_053', null),
       ('sys_core_data_table_054', null),
       ('sys_core_data_table_055', null),
       ('sys_core_data_table_056', null),
       ('sys_core_data_table_057', null),
       ('sys_core_data_table_058', null),
       ('sys_core_data_table_059', null),
       ('sys_core_data_table_060', null),
       ('sys_core_data_table_061', null),
       ('sys_core_data_table_062', null),
       ('sys_core_data_table_063', null),
       ('sys_core_data_table_064', null),
       ('sys_core_data_table_065', null),
       ('sys_core_data_table_066', null),
       ('sys_core_data_table_067', null),
       ('sys_core_data_table_068', null),
       ('sys_core_data_table_069', null),
       ('sys_core_data_table_070', null),
       ('sys_core_data_table_071', null),
       ('sys_core_data_table_072', null),
       ('sys_core_data_table_073', null),
       ('sys_core_data_table_074', null),
       ('sys_core_data_table_075', null),
       ('sys_core_data_table_076', null),
       ('sys_core_data_table_077', null),
       ('sys_core_data_table_078', null),
       ('sys_core_data_table_079', null),
       ('sys_core_data_table_080', null),
       ('sys_core_data_table_081', null),
       ('sys_core_data_table_082', null),
       ('sys_core_data_table_083', null),
       ('sys_core_data_table_084', null),
       ('sys_core_data_table_085', null),
       ('sys_core_data_table_086', null),
       ('sys_core_data_table_087', null),
       ('sys_core_data_table_088', null),
       ('sys_core_data_table_089', null),
       ('sys_core_data_table_090', null),
       ('sys_core_data_table_091', null),
       ('sys_core_data_table_092', null),
       ('sys_core_data_table_093', null),
       ('sys_core_data_table_094', null),
       ('sys_core_data_table_095', null),
       ('sys_core_data_table_096', null),
       ('sys_core_data_table_097', null),
       ('sys_core_data_table_098', null),
       ('sys_core_data_table_099', null),
       ('sys_core_data_table_100', null),
       ('sys_core_data_table_101', null),
       ('sys_core_data_table_102', null),
       ('sys_core_data_table_103', null),
       ('sys_core_data_table_104', null),
       ('sys_core_data_table_105', null),
       ('sys_core_data_table_106', null),
       ('sys_core_data_table_107', null),
       ('sys_core_data_table_108', null),
       ('sys_core_data_table_109', null),
       ('sys_core_data_table_110', null),
       ('sys_core_data_table_111', null),
       ('sys_core_data_table_112', null),
       ('sys_core_data_table_113', null),
       ('sys_core_data_table_114', null),
       ('sys_core_data_table_115', null),
       ('sys_core_data_table_116', null),
       ('sys_core_data_table_117', null),
       ('sys_core_data_table_118', null),
       ('sys_core_data_table_119', null),
       ('sys_core_data_table_120', null),
       ('sys_core_data_table_121', null),
       ('sys_core_data_table_122', null),
       ('sys_core_data_table_123', null),
       ('sys_core_data_table_124', null),
       ('sys_core_data_table_125', null),
       ('sys_core_data_table_126', null),
       ('sys_core_data_table_127', null),
       ('sys_core_data_table_128', null),
       ('sys_core_data_table_129', null),
       ('sys_core_data_table_130', null),
       ('sys_core_data_table_131', null),
       ('sys_core_data_table_132', null),
       ('sys_core_data_table_133', null),
       ('sys_core_data_table_134', null),
       ('sys_core_data_table_135', null),
       ('sys_core_data_table_136', null),
       ('sys_core_data_table_137', null),
       ('sys_core_data_table_138', null),
       ('sys_core_data_table_139', null),
       ('sys_core_data_table_140', null),
       ('sys_core_data_table_141', null),
       ('sys_core_data_table_142', null),
       ('sys_core_data_table_143', null),
       ('sys_core_data_table_144', null),
       ('sys_core_data_table_145', null),
       ('sys_core_data_table_146', null),
       ('sys_core_data_table_147', null),
       ('sys_core_data_table_148', null),
       ('sys_core_data_table_149', null),
       ('sys_core_data_table_150', null),
       ('sys_core_data_table_151', null),
       ('sys_core_data_table_152', null),
       ('sys_core_data_table_153', null),
       ('sys_core_data_table_154', null),
       ('sys_core_data_table_155', null),
       ('sys_core_data_table_156', null),
       ('sys_core_data_table_157', null),
       ('sys_core_data_table_158', null),
       ('sys_core_data_table_159', null),
       ('sys_core_data_table_160', null),
       ('sys_core_data_table_161', null),
       ('sys_core_data_table_162', null),
       ('sys_core_data_table_163', null),
       ('sys_core_data_table_164', null),
       ('sys_core_data_table_165', null),
       ('sys_core_data_table_166', null),
       ('sys_core_data_table_167', null),
       ('sys_core_data_table_168', null),
       ('sys_core_data_table_169', null),
       ('sys_core_data_table_170', null),
       ('sys_core_data_table_171', null),
       ('sys_core_data_table_172', null),
       ('sys_core_data_table_173', null),
       ('sys_core_data_table_174', null),
       ('sys_core_data_table_175', null),
       ('sys_core_data_table_176', null),
       ('sys_core_data_table_177', null),
       ('sys_core_data_table_178', null),
       ('sys_core_data_table_179', null),
       ('sys_core_data_table_180', null),
       ('sys_core_data_table_181', null),
       ('sys_core_data_table_182', null),
       ('sys_core_data_table_183', null),
       ('sys_core_data_table_184', null),
       ('sys_core_data_table_185', null),
       ('sys_core_data_table_186', null),
       ('sys_core_data_table_187', null),
       ('sys_core_data_table_188', null),
       ('sys_core_data_table_189', null),
       ('sys_core_data_table_190', null),
       ('sys_core_data_table_191', null),
       ('sys_core_data_table_192', null),
       ('sys_core_data_table_193', null),
       ('sys_core_data_table_194', null),
       ('sys_core_data_table_195', null),
       ('sys_core_data_table_196', null),
       ('sys_core_data_table_197', null),
       ('sys_core_data_table_198', null),
       ('sys_core_data_table_199', null),
       ('sys_core_data_table_200', null),
       ('sys_core_data_table_201', null),
       ('sys_core_data_table_202', null),
       ('sys_core_data_table_203', null),
       ('sys_core_data_table_204', null),
       ('sys_core_data_table_205', null),
       ('sys_core_data_table_206', null),
       ('sys_core_data_table_207', null),
       ('sys_core_data_table_208', null),
       ('sys_core_data_table_209', null),
       ('sys_core_data_table_210', null),
       ('sys_core_data_table_211', null),
       ('sys_core_data_table_212', null),
       ('sys_core_data_table_213', null),
       ('sys_core_data_table_214', null),
       ('sys_core_data_table_215', null),
       ('sys_core_data_table_216', null),
       ('sys_core_data_table_217', null),
       ('sys_core_data_table_218', null),
       ('sys_core_data_table_219', null),
       ('sys_core_data_table_220', null),
       ('sys_core_data_table_221', null),
       ('sys_core_data_table_222', null),
       ('sys_core_data_table_223', null),
       ('sys_core_data_table_224', null),
       ('sys_core_data_table_225', null),
       ('sys_core_data_table_226', null),
       ('sys_core_data_table_227', null),
       ('sys_core_data_table_228', null),
       ('sys_core_data_table_229', null),
       ('sys_core_data_table_230', null),
       ('sys_core_data_table_231', null),
       ('sys_core_data_table_232', null),
       ('sys_core_data_table_233', null),
       ('sys_core_data_table_234', null),
       ('sys_core_data_table_235', null),
       ('sys_core_data_table_236', null),
       ('sys_core_data_table_237', null),
       ('sys_core_data_table_238', null),
       ('sys_core_data_table_239', null),
       ('sys_core_data_table_240', null),
       ('sys_core_data_table_241', null),
       ('sys_core_data_table_242', null),
       ('sys_core_data_table_243', null),
       ('sys_core_data_table_244', null),
       ('sys_core_data_table_245', null),
       ('sys_core_data_table_246', null),
       ('sys_core_data_table_247', null),
       ('sys_core_data_table_248', null),
       ('sys_core_data_table_249', null),
       ('sys_core_data_table_250', null),
       ('sys_core_data_table_251', null),
       ('sys_core_data_table_252', null),
       ('sys_core_data_table_253', null),
       ('sys_core_data_table_254', null),
       ('sys_core_data_table_255', null),
       ('sys_core_data_table_256', null),
       ('sys_core_data_table_257', null),
       ('sys_core_data_table_258', null),
       ('sys_core_data_table_259', null),
       ('sys_core_data_table_260', null),
       ('sys_core_data_table_261', null),
       ('sys_core_data_table_262', null),
       ('sys_core_data_table_263', null),
       ('sys_core_data_table_264', null),
       ('sys_core_data_table_265', null),
       ('sys_core_data_table_266', null),
       ('sys_core_data_table_267', null),
       ('sys_core_data_table_268', null),
       ('sys_core_data_table_269', null),
       ('sys_core_data_table_270', null),
       ('sys_core_data_table_271', null),
       ('sys_core_data_table_272', null),
       ('sys_core_data_table_273', null),
       ('sys_core_data_table_274', null),
       ('sys_core_data_table_275', null),
       ('sys_core_data_table_276', null),
       ('sys_core_data_table_277', null),
       ('sys_core_data_table_278', null),
       ('sys_core_data_table_279', null),
       ('sys_core_data_table_280', null),
       ('sys_core_data_table_281', null),
       ('sys_core_data_table_282', null),
       ('sys_core_data_table_283', null),
       ('sys_core_data_table_284', null),
       ('sys_core_data_table_285', null),
       ('sys_core_data_table_286', null),
       ('sys_core_data_table_287', null),
       ('sys_core_data_table_288', null),
       ('sys_core_data_table_289', null),
       ('sys_core_data_table_290', null),
       ('sys_core_data_table_291', null),
       ('sys_core_data_table_292', null),
       ('sys_core_data_table_293', null),
       ('sys_core_data_table_294', null),
       ('sys_core_data_table_295', null),
       ('sys_core_data_table_296', null),
       ('sys_core_data_table_297', null),
       ('sys_core_data_table_298', null),
       ('sys_core_data_table_299', null),
       ('sys_core_data_table_300', null),
       ('sys_core_data_table_301', null),
       ('sys_core_data_table_302', null),
       ('sys_core_data_table_303', null),
       ('sys_core_data_table_304', null),
       ('sys_core_data_table_305', null),
       ('sys_core_data_table_306', null),
       ('sys_core_data_table_307', null),
       ('sys_core_data_table_308', null),
       ('sys_core_data_table_309', null),
       ('sys_core_data_table_310', null),
       ('sys_core_data_table_311', null),
       ('sys_core_data_table_312', null),
       ('sys_core_data_table_313', null),
       ('sys_core_data_table_314', null),
       ('sys_core_data_table_315', null),
       ('sys_core_data_table_316', null),
       ('sys_core_data_table_317', null),
       ('sys_core_data_table_318', null),
       ('sys_core_data_table_319', null),
       ('sys_core_data_table_320', null),
       ('sys_core_data_table_321', null),
       ('sys_core_data_table_322', null),
       ('sys_core_data_table_323', null),
       ('sys_core_data_table_324', null),
       ('sys_core_data_table_325', null),
       ('sys_core_data_table_326', null),
       ('sys_core_data_table_327', null),
       ('sys_core_data_table_328', null),
       ('sys_core_data_table_329', null),
       ('sys_core_data_table_330', null),
       ('sys_core_data_table_331', null),
       ('sys_core_data_table_332', null),
       ('sys_core_data_table_333', null),
       ('sys_core_data_table_334', null),
       ('sys_core_data_table_335', null),
       ('sys_core_data_table_336', null),
       ('sys_core_data_table_337', null),
       ('sys_core_data_table_338', null),
       ('sys_core_data_table_339', null),
       ('sys_core_data_table_340', null),
       ('sys_core_data_table_341', null),
       ('sys_core_data_table_342', null),
       ('sys_core_data_table_343', null),
       ('sys_core_data_table_344', null),
       ('sys_core_data_table_345', null),
       ('sys_core_data_table_346', null),
       ('sys_core_data_table_347', null),
       ('sys_core_data_table_348', null),
       ('sys_core_data_table_349', null),
       ('sys_core_data_table_350', null),
       ('sys_core_data_table_351', null),
       ('sys_core_data_table_352', null),
       ('sys_core_data_table_353', null),
       ('sys_core_data_table_354', null),
       ('sys_core_data_table_355', null),
       ('sys_core_data_table_356', null),
       ('sys_core_data_table_357', null),
       ('sys_core_data_table_358', null),
       ('sys_core_data_table_359', null),
       ('sys_core_data_table_360', null),
       ('sys_core_data_table_361', null),
       ('sys_core_data_table_362', null),
       ('sys_core_data_table_363', null),
       ('sys_core_data_table_364', null),
       ('sys_core_data_table_365', null),
       ('sys_core_data_table_366', null),
       ('sys_core_data_table_367', null),
       ('sys_core_data_table_368', null),
       ('sys_core_data_table_369', null),
       ('sys_core_data_table_370', null),
       ('sys_core_data_table_371', null),
       ('sys_core_data_table_372', null),
       ('sys_core_data_table_373', null),
       ('sys_core_data_table_374', null),
       ('sys_core_data_table_375', null),
       ('sys_core_data_table_376', null),
       ('sys_core_data_table_377', null),
       ('sys_core_data_table_378', null),
       ('sys_core_data_table_379', null),
       ('sys_core_data_table_380', null),
       ('sys_core_data_table_381', null),
       ('sys_core_data_table_382', null),
       ('sys_core_data_table_383', null),
       ('sys_core_data_table_384', null),
       ('sys_core_data_table_385', null),
       ('sys_core_data_table_386', null),
       ('sys_core_data_table_387', null),
       ('sys_core_data_table_388', null),
       ('sys_core_data_table_389', null),
       ('sys_core_data_table_390', null),
       ('sys_core_data_table_391', null),
       ('sys_core_data_table_392', null),
       ('sys_core_data_table_393', null),
       ('sys_core_data_table_394', null),
       ('sys_core_data_table_395', null),
       ('sys_core_data_table_396', null),
       ('sys_core_data_table_397', null),
       ('sys_core_data_table_398', null),
       ('sys_core_data_table_399', null),
       ('sys_core_data_table_400', null),
       ('sys_core_data_table_401', null),
       ('sys_core_data_table_402', null),
       ('sys_core_data_table_403', null),
       ('sys_core_data_table_404', null),
       ('sys_core_data_table_405', null),
       ('sys_core_data_table_406', null),
       ('sys_core_data_table_407', null),
       ('sys_core_data_table_408', null),
       ('sys_core_data_table_409', null),
       ('sys_core_data_table_410', null),
       ('sys_core_data_table_411', null),
       ('sys_core_data_table_412', null),
       ('sys_core_data_table_413', null),
       ('sys_core_data_table_414', null),
       ('sys_core_data_table_415', null),
       ('sys_core_data_table_416', null),
       ('sys_core_data_table_417', null),
       ('sys_core_data_table_418', null),
       ('sys_core_data_table_419', null),
       ('sys_core_data_table_420', null),
       ('sys_core_data_table_421', null),
       ('sys_core_data_table_422', null),
       ('sys_core_data_table_423', null),
       ('sys_core_data_table_424', null),
       ('sys_core_data_table_425', null),
       ('sys_core_data_table_426', null),
       ('sys_core_data_table_427', null),
       ('sys_core_data_table_428', null),
       ('sys_core_data_table_429', null),
       ('sys_core_data_table_430', null),
       ('sys_core_data_table_431', null),
       ('sys_core_data_table_432', null),
       ('sys_core_data_table_433', null),
       ('sys_core_data_table_434', null),
       ('sys_core_data_table_435', null),
       ('sys_core_data_table_436', null),
       ('sys_core_data_table_437', null),
       ('sys_core_data_table_438', null),
       ('sys_core_data_table_439', null),
       ('sys_core_data_table_440', null),
       ('sys_core_data_table_441', null),
       ('sys_core_data_table_442', null),
       ('sys_core_data_table_443', null),
       ('sys_core_data_table_444', null),
       ('sys_core_data_table_445', null),
       ('sys_core_data_table_446', null),
       ('sys_core_data_table_447', null),
       ('sys_core_data_table_448', null),
       ('sys_core_data_table_449', null),
       ('sys_core_data_table_450', null),
       ('sys_core_data_table_451', null),
       ('sys_core_data_table_452', null),
       ('sys_core_data_table_453', null),
       ('sys_core_data_table_454', null),
       ('sys_core_data_table_455', null),
       ('sys_core_data_table_456', null),
       ('sys_core_data_table_457', null),
       ('sys_core_data_table_458', null),
       ('sys_core_data_table_459', null),
       ('sys_core_data_table_460', null),
       ('sys_core_data_table_461', null),
       ('sys_core_data_table_462', null),
       ('sys_core_data_table_463', null),
       ('sys_core_data_table_464', null),
       ('sys_core_data_table_465', null),
       ('sys_core_data_table_466', null),
       ('sys_core_data_table_467', null),
       ('sys_core_data_table_468', null),
       ('sys_core_data_table_469', null),
       ('sys_core_data_table_470', null),
       ('sys_core_data_table_471', null),
       ('sys_core_data_table_472', null),
       ('sys_core_data_table_473', null),
       ('sys_core_data_table_474', null),
       ('sys_core_data_table_475', null),
       ('sys_core_data_table_476', null),
       ('sys_core_data_table_477', null),
       ('sys_core_data_table_478', null),
       ('sys_core_data_table_479', null),
       ('sys_core_data_table_480', null),
       ('sys_core_data_table_481', null),
       ('sys_core_data_table_482', null),
       ('sys_core_data_table_483', null),
       ('sys_core_data_table_484', null),
       ('sys_core_data_table_485', null),
       ('sys_core_data_table_486', null),
       ('sys_core_data_table_487', null),
       ('sys_core_data_table_488', null),
       ('sys_core_data_table_489', null),
       ('sys_core_data_table_490', null),
       ('sys_core_data_table_491', null),
       ('sys_core_data_table_492', null),
       ('sys_core_data_table_493', null),
       ('sys_core_data_table_494', null),
       ('sys_core_data_table_495', null),
       ('sys_core_data_table_496', null),
       ('sys_core_data_table_497', null),
       ('sys_core_data_table_498', null),
       ('sys_core_data_table_499', null),
       ('sys_core_data_table_500', null);


insert into hymn.sql_keyword (keyword)
values ('a'),
       ('abort'),
       ('abs'),
       ('absent'),
       ('absolute'),
       ('access'),
       ('according'),
       ('acos'),
       ('action'),
       ('ada'),
       ('add'),
       ('admin'),
       ('after'),
       ('aggregate'),
       ('all'),
       ('allocate'),
       ('also'),
       ('alter'),
       ('always'),
       ('analyse'),
       ('analyze'),
       ('and'),
       ('any'),
       ('are'),
       ('array'),
       ('array_agg'),
       ('array_max_cardinality'),
       ('as'),
       ('asc'),
       ('asensitive'),
       ('asin'),
       ('assertion'),
       ('assignment'),
       ('asymmetric'),
       ('at'),
       ('atan'),
       ('atomic'),
       ('attach'),
       ('attribute'),
       ('attributes'),
       ('authorization'),
       ('avg'),
       ('backward'),
       ('base64'),
       ('before'),
       ('begin'),
       ('begin_frame'),
       ('begin_partition'),
       ('bernoulli'),
       ('between'),
       ('bigint'),
       ('binary'),
       ('bit'),
       ('bit_length'),
       ('blob'),
       ('blocked'),
       ('bom'),
       ('boolean'),
       ('both'),
       ('breadth'),
       ('by'),
       ('c'),
       ('cache'),
       ('call'),
       ('called'),
       ('cardinality'),
       ('cascade'),
       ('cascaded'),
       ('case'),
       ('cast'),
       ('catalog'),
       ('catalog_name'),
       ('ceil'),
       ('ceiling'),
       ('chain'),
       ('chaining'),
       ('char'),
       ('character'),
       ('characteristics'),
       ('characters'),
       ('character_length'),
       ('character_set_catalog'),
       ('character_set_name'),
       ('character_set_schema'),
       ('char_length'),
       ('check'),
       ('checkpoint'),
       ('class'),
       ('classifier'),
       ('class_origin'),
       ('clob'),
       ('close'),
       ('cluster'),
       ('coalesce'),
       ('cobol'),
       ('collate'),
       ('collation'),
       ('collation_catalog'),
       ('collation_name'),
       ('collation_schema'),
       ('collect'),
       ('column'),
       ('columns'),
       ('column_name'),
       ('command_function'),
       ('command_function_code'),
       ('comment'),
       ('comments'),
       ('commit'),
       ('committed'),
       ('concurrently'),
       ('condition'),
       ('conditional'),
       ('condition_number'),
       ('configuration'),
       ('conflict'),
       ('connect'),
       ('connection'),
       ('connection_name'),
       ('constraint'),
       ('constraints'),
       ('constraint_catalog'),
       ('constraint_name'),
       ('constraint_schema'),
       ('constructor'),
       ('contains'),
       ('content'),
       ('continue'),
       ('control'),
       ('conversion'),
       ('convert'),
       ('copy'),
       ('corr'),
       ('corresponding'),
       ('cos'),
       ('cosh'),
       ('cost'),
       ('count'),
       ('covar_pop'),
       ('covar_samp'),
       ('create'),
       ('cross'),
       ('csv'),
       ('cube'),
       ('cume_dist'),
       ('current'),
       ('current_catalog'),
       ('current_date'),
       ('current_default_transform_group'),
       ('current_path'),
       ('current_role'),
       ('current_row'),
       ('current_schema'),
       ('current_time'),
       ('current_timestamp'),
       ('current_transform_group_for_type'),
       ('current_user'),
       ('cursor'),
       ('cursor_name'),
       ('cycle'),
       ('data'),
       ('database'),
       ('datalink'),
       ('date'),
       ('datetime_interval_code'),
       ('datetime_interval_precision'),
       ('day'),
       ('db'),
       ('deallocate'),
       ('dec'),
       ('decfloat'),
       ('decimal'),
       ('declare'),
       ('default'),
       ('defaults'),
       ('deferrable'),
       ('deferred'),
       ('define'),
       ('defined'),
       ('definer'),
       ('degree'),
       ('delete'),
       ('delimiter'),
       ('delimiters'),
       ('dense_rank'),
       ('depends'),
       ('depth'),
       ('deref'),
       ('derived'),
       ('desc'),
       ('describe'),
       ('descriptor'),
       ('detach'),
       ('deterministic'),
       ('diagnostics'),
       ('dictionary'),
       ('disable'),
       ('discard'),
       ('disconnect'),
       ('dispatch'),
       ('distinct'),
       ('dlnewcopy'),
       ('dlpreviouscopy'),
       ('dlurlcomplete'),
       ('dlurlcompleteonly'),
       ('dlurlcompletewrite'),
       ('dlurlpath'),
       ('dlurlpathonly'),
       ('dlurlpathwrite'),
       ('dlurlscheme'),
       ('dlurlserver'),
       ('dlvalue'),
       ('do'),
       ('document'),
       ('domain'),
       ('double'),
       ('drop'),
       ('dynamic'),
       ('dynamic_function'),
       ('dynamic_function_code'),
       ('each'),
       ('element'),
       ('else'),
       ('empty'),
       ('enable'),
       ('encoding'),
       ('encrypted'),
       ('end'),
       ('end-exec'),
       ('end_frame'),
       ('end_partition'),
       ('enforced'),
       ('enum'),
       ('equals'),
       ('error'),
       ('escape'),
       ('event'),
       ('every'),
       ('except'),
       ('exception'),
       ('exclude'),
       ('excluding'),
       ('exclusive'),
       ('exec'),
       ('execute'),
       ('exists'),
       ('exp'),
       ('explain'),
       ('expression'),
       ('extension'),
       ('external'),
       ('extract'),
       ('false'),
       ('family'),
       ('fetch'),
       ('file'),
       ('filter'),
       ('final'),
       ('finish'),
       ('first'),
       ('first_value'),
       ('flag'),
       ('float'),
       ('floor'),
       ('following'),
       ('for'),
       ('force'),
       ('foreign'),
       ('format'),
       ('fortran'),
       ('forward'),
       ('found'),
       ('frame_row'),
       ('free'),
       ('freeze'),
       ('from'),
       ('fs'),
       ('fulfill'),
       ('full'),
       ('function'),
       ('functions'),
       ('fusion'),
       ('g'),
       ('general'),
       ('generated'),
       ('get'),
       ('global'),
       ('go'),
       ('goto'),
       ('grant'),
       ('granted'),
       ('greatest'),
       ('group'),
       ('grouping'),
       ('groups'),
       ('handler'),
       ('having'),
       ('header'),
       ('hex'),
       ('hierarchy'),
       ('hold'),
       ('hour'),
       ('id'),
       ('identity'),
       ('if'),
       ('ignore'),
       ('ilike'),
       ('immediate'),
       ('immediately'),
       ('immutable'),
       ('implementation'),
       ('implicit'),
       ('import'),
       ('in'),
       ('include'),
       ('including'),
       ('increment'),
       ('indent'),
       ('index'),
       ('indexes'),
       ('indicator'),
       ('inherit'),
       ('inherits'),
       ('initial'),
       ('initially'),
       ('inline'),
       ('inner'),
       ('inout'),
       ('input'),
       ('insensitive'),
       ('insert'),
       ('instance'),
       ('instantiable'),
       ('instead'),
       ('int'),
       ('integer'),
       ('integrity'),
       ('intersect'),
       ('intersection'),
       ('interval'),
       ('into'),
       ('invoker'),
       ('is'),
       ('isnull'),
       ('isolation'),
       ('join'),
       ('json'),
       ('json_array'),
       ('json_arrayagg'),
       ('json_exists'),
       ('json_object'),
       ('json_objectagg'),
       ('json_query'),
       ('json_table'),
       ('json_table_primitive'),
       ('json_value'),
       ('k'),
       ('keep'),
       ('key'),
       ('keys'),
       ('key_member'),
       ('key_type'),
       ('label'),
       ('lag'),
       ('language'),
       ('large'),
       ('last'),
       ('last_value'),
       ('lateral'),
       ('lead'),
       ('leading'),
       ('leakproof'),
       ('least'),
       ('left'),
       ('length'),
       ('level'),
       ('library'),
       ('like'),
       ('like_regex'),
       ('limit'),
       ('link'),
       ('listagg'),
       ('listen'),
       ('ln'),
       ('load'),
       ('local'),
       ('localtime'),
       ('localtimestamp'),
       ('location'),
       ('locator'),
       ('lock'),
       ('locked'),
       ('log'),
       ('log10'),
       ('logged'),
       ('lower'),
       ('m'),
       ('map'),
       ('mapping'),
       ('match'),
       ('matched'),
       ('matches'),
       ('match_number'),
       ('match_recognize'),
       ('materialized'),
       ('max'),
       ('maxvalue'),
       ('measures'),
       ('member'),
       ('merge'),
       ('message_length'),
       ('message_octet_length'),
       ('message_text'),
       ('method'),
       ('min'),
       ('minute'),
       ('minvalue'),
       ('mod'),
       ('mode'),
       ('modifies'),
       ('module'),
       ('month'),
       ('more'),
       ('move'),
       ('multiset'),
       ('mumps'),
       ('name'),
       ('names'),
       ('namespace'),
       ('national'),
       ('natural'),
       ('nchar'),
       ('nclob'),
       ('nested'),
       ('nesting'),
       ('new'),
       ('next'),
       ('nfc'),
       ('nfd'),
       ('nfkc'),
       ('nfkd'),
       ('nil'),
       ('no'),
       ('none'),
       ('normalize'),
       ('normalized'),
       ('not'),
       ('nothing'),
       ('notify'),
       ('notnull'),
       ('nowait'),
       ('nth_value'),
       ('ntile'),
       ('null'),
       ('nullable'),
       ('nullif'),
       ('nulls'),
       ('number'),
       ('numeric'),
       ('object'),
       ('occurrences_regex'),
       ('octets'),
       ('octet_length'),
       ('of'),
       ('off'),
       ('offset'),
       ('oids'),
       ('old'),
       ('omit'),
       ('on'),
       ('one'),
       ('only'),
       ('open'),
       ('operator'),
       ('option'),
       ('options'),
       ('or'),
       ('order'),
       ('ordering'),
       ('ordinality'),
       ('others'),
       ('out'),
       ('outer'),
       ('output'),
       ('over'),
       ('overflow'),
       ('overlaps'),
       ('overlay'),
       ('overriding'),
       ('owned'),
       ('owner'),
       ('p'),
       ('pad'),
       ('parallel'),
       ('parameter'),
       ('parameter_mode'),
       ('parameter_name'),
       ('parameter_ordinal_position'),
       ('parameter_specific_catalog'),
       ('parameter_specific_name'),
       ('parameter_specific_schema'),
       ('parser'),
       ('partial'),
       ('partition'),
       ('pascal'),
       ('pass'),
       ('passing'),
       ('passthrough'),
       ('password'),
       ('past'),
       ('path'),
       ('pattern'),
       ('per'),
       ('percent'),
       ('percentile_cont'),
       ('percentile_disc'),
       ('percent_rank'),
       ('period'),
       ('permission'),
       ('permute'),
       ('placing'),
       ('plan'),
       ('plans'),
       ('pli'),
       ('policy'),
       ('portion'),
       ('position'),
       ('position_regex'),
       ('power'),
       ('precedes'),
       ('preceding'),
       ('precision'),
       ('prepare'),
       ('prepared'),
       ('preserve'),
       ('primary'),
       ('prior'),
       ('private'),
       ('privileges'),
       ('procedural'),
       ('procedure'),
       ('procedures'),
       ('program'),
       ('prune'),
       ('ptf'),
       ('public'),
       ('publication'),
       ('quote'),
       ('quotes'),
       ('range'),
       ('rank'),
       ('read'),
       ('reads'),
       ('real'),
       ('reassign'),
       ('recheck'),
       ('recovery'),
       ('recursive'),
       ('ref'),
       ('references'),
       ('referencing'),
       ('refresh'),
       ('regr_avgx'),
       ('regr_avgy'),
       ('regr_count'),
       ('regr_intercept'),
       ('regr_r2'),
       ('regr_slope'),
       ('regr_sxx'),
       ('regr_sxy'),
       ('regr_syy'),
       ('reindex'),
       ('relative'),
       ('release'),
       ('rename'),
       ('repeatable'),
       ('replace'),
       ('replica'),
       ('requiring'),
       ('reset'),
       ('respect'),
       ('restart'),
       ('restore'),
       ('restrict'),
       ('result'),
       ('return'),
       ('returned_cardinality'),
       ('returned_length'),
       ('returned_octet_length'),
       ('returned_sqlstate'),
       ('returning'),
       ('returns'),
       ('revoke'),
       ('right'),
       ('role'),
       ('rollback'),
       ('rollup'),
       ('routine'),
       ('routines'),
       ('routine_catalog'),
       ('routine_name'),
       ('routine_schema'),
       ('row'),
       ('rows'),
       ('row_count'),
       ('row_number'),
       ('rule'),
       ('running'),
       ('savepoint'),
       ('scalar'),
       ('scale'),
       ('schema'),
       ('schemas'),
       ('schema_name'),
       ('scope'),
       ('scope_catalog'),
       ('scope_name'),
       ('scope_schema'),
       ('scroll'),
       ('search'),
       ('second'),
       ('section'),
       ('security'),
       ('seek'),
       ('select'),
       ('selective'),
       ('self'),
       ('sensitive'),
       ('sequence'),
       ('sequences'),
       ('serializable'),
       ('server'),
       ('server_name'),
       ('session'),
       ('session_user'),
       ('set'),
       ('setof'),
       ('sets'),
       ('share'),
       ('show'),
       ('similar'),
       ('simple'),
       ('sin'),
       ('sinh'),
       ('size'),
       ('skip'),
       ('smallint'),
       ('snapshot'),
       ('some'),
       ('source'),
       ('space'),
       ('specific'),
       ('specifictype'),
       ('specific_name'),
       ('sql'),
       ('sqlcode'),
       ('sqlerror'),
       ('sqlexception'),
       ('sqlstate'),
       ('sqlwarning'),
       ('sqrt'),
       ('stable'),
       ('standalone'),
       ('start'),
       ('state'),
       ('statement'),
       ('static'),
       ('statistics'),
       ('stddev_pop'),
       ('stddev_samp'),
       ('stdin'),
       ('stdout'),
       ('storage'),
       ('stored'),
       ('strict'),
       ('string'),
       ('strip'),
       ('structure'),
       ('style'),
       ('subclass_origin'),
       ('submultiset'),
       ('subscription'),
       ('subset'),
       ('substring'),
       ('substring_regex'),
       ('succeeds'),
       ('sum'),
       ('support'),
       ('symmetric'),
       ('sysid'),
       ('system'),
       ('system_time'),
       ('system_user'),
       ('t'),
       ('table'),
       ('tables'),
       ('tablesample'),
       ('tablespace'),
       ('table_name'),
       ('tan'),
       ('tanh'),
       ('temp'),
       ('template'),
       ('temporary'),
       ('text'),
       ('then'),
       ('through'),
       ('ties'),
       ('time'),
       ('timestamp'),
       ('timezone_hour'),
       ('timezone_minute'),
       ('to'),
       ('token'),
       ('top_level_count'),
       ('trailing'),
       ('transaction'),
       ('transactions_committed'),
       ('transactions_rolled_back'),
       ('transaction_active'),
       ('transform'),
       ('transforms'),
       ('translate'),
       ('translate_regex'),
       ('translation'),
       ('treat'),
       ('trigger'),
       ('trigger_catalog'),
       ('trigger_name'),
       ('trigger_schema'),
       ('trim'),
       ('trim_array'),
       ('true'),
       ('truncate'),
       ('trusted'),
       ('type'),
       ('types'),
       ('uescape'),
       ('unbounded'),
       ('uncommitted'),
       ('unconditional'),
       ('under'),
       ('unencrypted'),
       ('union'),
       ('unique'),
       ('unknown'),
       ('unlink'),
       ('unlisten'),
       ('unlogged'),
       ('unmatched'),
       ('unnamed'),
       ('unnest'),
       ('until'),
       ('untyped'),
       ('update'),
       ('upper'),
       ('uri'),
       ('usage'),
       ('user'),
       ('user_defined_type_catalog'),
       ('user_defined_type_code'),
       ('user_defined_type_name'),
       ('user_defined_type_schema'),
       ('using'),
       ('utf16'),
       ('utf32'),
       ('utf8'),
       ('vacuum'),
       ('valid'),
       ('validate'),
       ('validator'),
       ('value'),
       ('values'),
       ('value_of'),
       ('varbinary'),
       ('varchar'),
       ('variadic'),
       ('varying'),
       ('var_pop'),
       ('var_samp'),
       ('verbose'),
       ('version'),
       ('versioning'),
       ('view'),
       ('views'),
       ('volatile'),
       ('when'),
       ('whenever'),
       ('where'),
       ('whitespace'),
       ('width_bucket'),
       ('window'),
       ('with'),
       ('within'),
       ('without'),
       ('work'),
       ('wrapper'),
       ('write'),
       ('xml'),
       ('xmlagg'),
       ('xmlattributes'),
       ('xmlbinary'),
       ('xmlcast'),
       ('xmlcomment'),
       ('xmlconcat'),
       ('xmldeclaration'),
       ('xmldocument'),
       ('xmlelement'),
       ('xmlexists'),
       ('xmlforest'),
       ('xmliterate'),
       ('xmlnamespaces'),
       ('xmlparse'),
       ('xmlpi'),
       ('xmlquery'),
       ('xmlroot'),
       ('xmlschema'),
       ('xmlserialize'),
       ('xmltable'),
       ('xmltext'),
       ('xmlvalidate'),
       ('year'),
       ('yes'),
       ('zone');