db:
  url: jdbc:postgresql://localhost:5432/test
  user: test
  password: 123456
  driver: org.postgresql.Driver
schema: hymn
packageName: github.afezeria.hymn.admin
moduleName: admin
tableRegex: ^core(?!_data_table).*(?<!history)$
templates: [
    Controller,
    Dto,
    Entity,
    Dao,
    DaoImpl,
    Table
]
systemOutput: false
outputPath: